name: Chess Stats Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: "30 18 * * *"
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme:
    name: Update readme with chess stats
    runs-on: ubuntu-latest
    steps:
      - uses: Prathamesh-B/chess-stats-readme@master
        with:
          GH_TOKEN: ${{ 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 }}
          CHESS_USERNAME: 'KenHa'
          RATING_TYPE : 'best'